######################################################################
# Automatically generated by qmake (3.1) Mon Mar 13 17:32:46 2017
######################################################################

QT += widgets testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += TestInstructionResolver.cpp
