#############################################################################
# Makefile for building: bin/PISA
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  PISA.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile PISA.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/webrown/PISA"'
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=c++0x -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -Isrc/gui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PISA1.0.0
DISTDIR = /home/webrown/PISA/build/PISA1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu -lQt5Widgets -lQt5Gui -lQt5Test -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/Utility.cpp \
		test/TestAssembler.cpp \
		test/TestInstructionResolver.cpp \
		src/assembler/Assembler.cpp \
		src/assembler/Disassembler.cpp \
		src/assembler/InstructionResolver.cpp \
		src/computer/Computer.cpp \
		src/gui/CacheView.cpp \
		src/gui/CodeEditor.cpp \
		src/gui/EditorTab.cpp \
		src/gui/HighLighter.cpp \
		src/gui/MainWindow.cpp \
		src/gui/MemoryView.cpp \
		src/gui/MiscDialog.cpp \
		src/gui/PreferenceDialog.cpp \
		src/gui/RegisterView.cpp \
		src/memory/Cache.cpp \
		src/memory/MainMemory.cpp \
		src/memory/MemoryInterface.cpp \
		src/memory/MemoryStructure.cpp \
		src/memory/QueryResult.cpp \
		src/memory/Register.cpp \
		src/memory/serialization.cpp \
		src/pipeline/Baseline.cpp \
		src/pipeline/spliceMachineCode.cpp \
		src/pipeline/StageData.cpp build/qrc_pisa.cpp \
		build/moc_TestAssembler.cpp \
		build/moc_TestInstructionResolver.cpp \
		build/moc_Assembler.cpp \
		build/moc_CacheView.cpp \
		build/moc_CodeEditor.cpp \
		build/moc_EditorTab.cpp \
		build/moc_HighLighter.cpp \
		build/moc_MainWindow.cpp \
		build/moc_MemoryView.cpp \
		build/moc_MiscDialog.cpp \
		build/moc_PreferenceDialog.cpp \
		build/moc_RegisterView.cpp
OBJECTS       = build/main.o \
		build/Utility.o \
		build/TestAssembler.o \
		build/TestInstructionResolver.o \
		build/Assembler.o \
		build/Disassembler.o \
		build/InstructionResolver.o \
		build/Computer.o \
		build/CacheView.o \
		build/CodeEditor.o \
		build/EditorTab.o \
		build/HighLighter.o \
		build/MainWindow.o \
		build/MemoryView.o \
		build/MiscDialog.o \
		build/PreferenceDialog.o \
		build/RegisterView.o \
		build/Cache.o \
		build/MainMemory.o \
		build/MemoryInterface.o \
		build/MemoryStructure.o \
		build/QueryResult.o \
		build/Register.o \
		build/serialization.o \
		build/Baseline.o \
		build/spliceMachineCode.o \
		build/StageData.o \
		build/qrc_pisa.o \
		build/moc_TestAssembler.o \
		build/moc_TestInstructionResolver.o \
		build/moc_Assembler.o \
		build/moc_CacheView.o \
		build/moc_CodeEditor.o \
		build/moc_EditorTab.o \
		build/moc_HighLighter.o \
		build/moc_MainWindow.o \
		build/moc_MemoryView.o \
		build/moc_MiscDialog.o \
		build/moc_PreferenceDialog.o \
		build/moc_RegisterView.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PISA.pro src/Utility.h \
		test/TestAssembler.h \
		test/TestInstructionResolver.h \
		src/assembler/Assembler.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/InstructionResolver.h \
		src/assembler/Problem.h \
		src/assembler/ProgramManagerX.h \
		src/assembler/Warning.h \
		src/computer/Architecture.h \
		src/computer/BreakPoint.h \
		src/computer/Computer.h \
		src/computer/Status.h \
		src/gui/CacheView.h \
		src/gui/CodeEditor.h \
		src/gui/EditorTab.h \
		src/gui/HexSpinBox.h \
		src/gui/HighLighter.h \
		src/gui/MainWindow.h \
		src/gui/MemoryView.h \
		src/gui/MiscDialog.h \
		src/gui/PreferenceDialog.h \
		src/gui/RegisterView.h \
		src/memory/Cache.h \
		src/memory/MainMemory.h \
		src/memory/MemoryInterface.h \
		src/memory/MemoryStructure.h \
		src/memory/QueryResult.h \
		src/memory/Register.h \
		src/memory/serialization.h \
		src/memory/Value.h \
		src/pipeline/Banana.h \
		src/pipeline/Baseline.h \
		src/pipeline/Pipeline.h \
		src/pipeline/PipelineGlobals.h \
		src/pipeline/spliceMachineCode.h \
		src/pipeline/StageData.h src/main.cpp \
		src/Utility.cpp \
		test/TestAssembler.cpp \
		test/TestInstructionResolver.cpp \
		src/assembler/Assembler.cpp \
		src/assembler/Disassembler.cpp \
		src/assembler/InstructionResolver.cpp \
		src/computer/Computer.cpp \
		src/gui/CacheView.cpp \
		src/gui/CodeEditor.cpp \
		src/gui/EditorTab.cpp \
		src/gui/HighLighter.cpp \
		src/gui/MainWindow.cpp \
		src/gui/MemoryView.cpp \
		src/gui/MiscDialog.cpp \
		src/gui/PreferenceDialog.cpp \
		src/gui/RegisterView.cpp \
		src/memory/Cache.cpp \
		src/memory/MainMemory.cpp \
		src/memory/MemoryInterface.cpp \
		src/memory/MemoryStructure.cpp \
		src/memory/QueryResult.cpp \
		src/memory/Register.cpp \
		src/memory/serialization.cpp \
		src/pipeline/Baseline.cpp \
		src/pipeline/spliceMachineCode.cpp \
		src/pipeline/StageData.cpp
QMAKE_TARGET  = PISA
DESTDIR       = bin/#avoid trailing-slash linebreak
TARGET        = bin/PISA


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): src/gui/ui_newcachedialog.h src/gui/ui_newfiledialog.h src/gui/ui_pisa.h src/gui/ui_preferencedialog.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PISA.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PISA.pro \
		rsc/pisa.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Test.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile PISA.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
PISA.pro:
rsc/pisa.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Test.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PISA.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents rsc/pisa.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/Utility.h test/TestAssembler.h test/TestInstructionResolver.h src/assembler/Assembler.h src/assembler/ConditionResolver.h src/assembler/Disassembler.h src/assembler/InstructionResolver.h src/assembler/Problem.h src/assembler/ProgramManagerX.h src/assembler/Warning.h src/computer/Architecture.h src/computer/BreakPoint.h src/computer/Computer.h src/computer/Status.h src/gui/CacheView.h src/gui/CodeEditor.h src/gui/EditorTab.h src/gui/HexSpinBox.h src/gui/HighLighter.h src/gui/MainWindow.h src/gui/MemoryView.h src/gui/MiscDialog.h src/gui/PreferenceDialog.h src/gui/RegisterView.h src/memory/Cache.h src/memory/MainMemory.h src/memory/MemoryInterface.h src/memory/MemoryStructure.h src/memory/QueryResult.h src/memory/Register.h src/memory/serialization.h src/memory/Value.h src/pipeline/Banana.h src/pipeline/Baseline.h src/pipeline/Pipeline.h src/pipeline/PipelineGlobals.h src/pipeline/spliceMachineCode.h src/pipeline/StageData.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Utility.cpp test/TestAssembler.cpp test/TestInstructionResolver.cpp src/assembler/Assembler.cpp src/assembler/Disassembler.cpp src/assembler/InstructionResolver.cpp src/computer/Computer.cpp src/gui/CacheView.cpp src/gui/CodeEditor.cpp src/gui/EditorTab.cpp src/gui/HighLighter.cpp src/gui/MainWindow.cpp src/gui/MemoryView.cpp src/gui/MiscDialog.cpp src/gui/PreferenceDialog.cpp src/gui/RegisterView.cpp src/memory/Cache.cpp src/memory/MainMemory.cpp src/memory/MemoryInterface.cpp src/memory/MemoryStructure.cpp src/memory/QueryResult.cpp src/memory/Register.cpp src/memory/serialization.cpp src/pipeline/Baseline.cpp src/pipeline/spliceMachineCode.cpp src/pipeline/StageData.cpp $(DISTDIR)/
	$(COPY_FILE) --parents rsc/ui/newcachedialog.ui rsc/ui/newfiledialog.ui rsc/ui/pisa.ui rsc/ui/preferencedialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: $(first) copydata

copydata:
	cp src/assembler/DefaultMacro src/assembler/DefaultAlias bin

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: build/qrc_pisa.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_pisa.cpp
build/qrc_pisa.cpp: rsc/pisa.qrc \
		rsc/img/forward2.png \
		rsc/img/backward2.png \
		rsc/img/save_all2.png \
		rsc/img/new2.png \
		rsc/img/new2.png \
		rsc/img/play2.png \
		rsc/img/upload2.png \
		rsc/img/build_all2.png \
		rsc/img/build2.png \
		rsc/img/save2.png \
		rsc/img/save2.png \
		rsc/img/open2.png \
		rsc/img/open2.png \
		rsc/img/pause2.png \
		rsc/img/stop2.png \
		rsc/img/icon.png \
		rsc/img/stop.png \
		rsc/img/save.png \
		rsc/img/open.png \
		rsc/img/play.png \
		rsc/img/build_all.png \
		rsc/img/forward.png \
		rsc/img/backward.png \
		rsc/img/build.png \
		rsc/img/new.png \
		rsc/img/pause.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name pisa rsc/pisa.qrc -o build/qrc_pisa.cpp

compiler_moc_header_make_all: build/moc_TestAssembler.cpp build/moc_TestInstructionResolver.cpp build/moc_Assembler.cpp build/moc_CacheView.cpp build/moc_CodeEditor.cpp build/moc_EditorTab.cpp build/moc_HighLighter.cpp build/moc_MainWindow.cpp build/moc_MemoryView.cpp build/moc_MiscDialog.cpp build/moc_PreferenceDialog.cpp build/moc_RegisterView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_TestAssembler.cpp build/moc_TestInstructionResolver.cpp build/moc_Assembler.cpp build/moc_CacheView.cpp build/moc_CodeEditor.cpp build/moc_EditorTab.cpp build/moc_HighLighter.cpp build/moc_MainWindow.cpp build/moc_MemoryView.cpp build/moc_MiscDialog.cpp build/moc_PreferenceDialog.cpp build/moc_RegisterView.cpp
build/moc_TestAssembler.cpp: src/assembler/Assembler.h \
		src/assembler/Problem.h \
		src/computer/Architecture.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		test/TestAssembler.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include test/TestAssembler.h -o build/moc_TestAssembler.cpp

build/moc_TestInstructionResolver.cpp: src/assembler/InstructionResolver.h \
		src/Utility.h \
		test/TestInstructionResolver.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include test/TestInstructionResolver.h -o build/moc_TestInstructionResolver.cpp

build/moc_Assembler.cpp: src/assembler/Problem.h \
		src/computer/Architecture.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Assembler.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/assembler/Assembler.h -o build/moc_Assembler.cpp

build/moc_CacheView.cpp: src/memory/Cache.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/gui/CacheView.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/CacheView.h -o build/moc_CacheView.cpp

build/moc_CodeEditor.cpp: src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/gui/CodeEditor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/CodeEditor.h -o build/moc_CodeEditor.cpp

build/moc_EditorTab.cpp: src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/gui/EditorTab.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/EditorTab.h -o build/moc_EditorTab.cpp

build/moc_HighLighter.cpp: src/gui/HighLighter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/HighLighter.h -o build/moc_HighLighter.cpp

build/moc_MainWindow.cpp: src/gui/ui_pisa.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h \
		src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/gui/PreferenceDialog.h \
		src/gui/ui_preferencedialog.h \
		src/gui/MainWindow.h \
		src/gui/CacheView.h \
		src/assembler/Assembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/ProgramManagerX.h \
		src/gui/HexSpinBox.h \
		src/gui/MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/MainWindow.h -o build/moc_MainWindow.cpp

build/moc_MemoryView.cpp: src/memory/MainMemory.h \
		src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/gui/HexSpinBox.h \
		src/gui/MemoryView.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/MemoryView.h -o build/moc_MemoryView.cpp

build/moc_MiscDialog.cpp: src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/memory/Cache.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/gui/MiscDialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/MiscDialog.h -o build/moc_MiscDialog.cpp

build/moc_PreferenceDialog.cpp: src/gui/ui_preferencedialog.h \
		src/gui/MainWindow.h \
		src/gui/ui_pisa.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h \
		src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/gui/PreferenceDialog.h \
		src/gui/CacheView.h \
		src/assembler/Assembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/ProgramManagerX.h \
		src/gui/HexSpinBox.h \
		src/gui/PreferenceDialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/PreferenceDialog.h -o build/moc_PreferenceDialog.cpp

build/moc_RegisterView.cpp: src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/gui/RegisterView.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/webrown/PISA -I/home/webrown/PISA -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/RegisterView.h -o build/moc_RegisterView.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/gui/ui_newcachedialog.h src/gui/ui_newfiledialog.h src/gui/ui_pisa.h src/gui/ui_preferencedialog.h
compiler_uic_clean:
	-$(DEL_FILE) src/gui/ui_newcachedialog.h src/gui/ui_newfiledialog.h src/gui/ui_pisa.h src/gui/ui_preferencedialog.h
src/gui/ui_newcachedialog.h: rsc/ui/newcachedialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic rsc/ui/newcachedialog.ui -o src/gui/ui_newcachedialog.h

src/gui/ui_newfiledialog.h: rsc/ui/newfiledialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic rsc/ui/newfiledialog.ui -o src/gui/ui_newfiledialog.h

src/gui/ui_pisa.h: rsc/ui/pisa.ui \
		src/gui/EditorTab.h \
		src/gui/HexSpinBox.h \
		src/gui/MemoryView.h \
		src/gui/RegisterView.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/memory/MainMemory.h \
		src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/gui/HexSpinBox.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic rsc/ui/pisa.ui -o src/gui/ui_pisa.h

src/gui/ui_preferencedialog.h: rsc/ui/preferencedialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic rsc/ui/preferencedialog.ui -o src/gui/ui_preferencedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/main.o: src/main.cpp src/gui/MainWindow.h \
		src/gui/ui_pisa.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h \
		src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/gui/PreferenceDialog.h \
		src/gui/ui_preferencedialog.h \
		src/gui/CacheView.h \
		src/assembler/Assembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/ProgramManagerX.h \
		src/gui/HexSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/Utility.o: src/Utility.cpp src/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Utility.o src/Utility.cpp

build/TestAssembler.o: test/TestAssembler.cpp test/TestAssembler.h \
		src/assembler/Assembler.h \
		src/assembler/Problem.h \
		src/computer/Architecture.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TestAssembler.o test/TestAssembler.cpp

build/TestInstructionResolver.o: test/TestInstructionResolver.cpp test/TestInstructionResolver.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TestInstructionResolver.o test/TestInstructionResolver.cpp

build/Assembler.o: src/assembler/Assembler.cpp src/assembler/Assembler.h \
		src/assembler/Problem.h \
		src/computer/Architecture.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Assembler.o src/assembler/Assembler.cpp

build/Disassembler.o: src/assembler/Disassembler.cpp src/assembler/Disassembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Disassembler.o src/assembler/Disassembler.cpp

build/InstructionResolver.o: src/assembler/InstructionResolver.cpp src/assembler/InstructionResolver.h \
		src/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/InstructionResolver.o src/assembler/InstructionResolver.cpp

build/Computer.o: src/computer/Computer.cpp src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Computer.o src/computer/Computer.cpp

build/CacheView.o: src/gui/CacheView.cpp src/gui/CacheView.h \
		src/memory/Cache.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CacheView.o src/gui/CacheView.cpp

build/CodeEditor.o: src/gui/CodeEditor.cpp src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CodeEditor.o src/gui/CodeEditor.cpp

build/EditorTab.o: src/gui/EditorTab.cpp src/gui/EditorTab.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/EditorTab.o src/gui/EditorTab.cpp

build/HighLighter.o: src/gui/HighLighter.cpp src/gui/HighLighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/HighLighter.o src/gui/HighLighter.cpp

build/MainWindow.o: src/gui/MainWindow.cpp src/gui/MainWindow.h \
		src/gui/ui_pisa.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h \
		src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/gui/PreferenceDialog.h \
		src/gui/ui_preferencedialog.h \
		src/gui/CacheView.h \
		src/assembler/Assembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/ProgramManagerX.h \
		src/gui/HexSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o src/gui/MainWindow.cpp

build/MemoryView.o: src/gui/MemoryView.cpp src/gui/MemoryView.h \
		src/memory/MainMemory.h \
		src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/gui/HexSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MemoryView.o src/gui/MemoryView.cpp

build/MiscDialog.o: src/gui/MiscDialog.cpp src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/memory/Cache.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MiscDialog.o src/gui/MiscDialog.cpp

build/PreferenceDialog.o: src/gui/PreferenceDialog.cpp src/gui/PreferenceDialog.h \
		src/gui/ui_preferencedialog.h \
		src/gui/MainWindow.h \
		src/gui/ui_pisa.h \
		src/gui/CodeEditor.h \
		src/gui/HighLighter.h \
		src/assembler/Problem.h \
		src/computer/Computer.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/BreakPoint.h \
		src/computer/Status.h \
		src/gui/MiscDialog.h \
		src/gui/ui_newcachedialog.h \
		src/gui/ui_newfiledialog.h \
		src/gui/CacheView.h \
		src/assembler/Assembler.h \
		src/assembler/InstructionResolver.h \
		src/Utility.h \
		src/assembler/ConditionResolver.h \
		src/assembler/Disassembler.h \
		src/assembler/ProgramManagerX.h \
		src/gui/HexSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/PreferenceDialog.o src/gui/PreferenceDialog.cpp

build/RegisterView.o: src/gui/RegisterView.cpp src/gui/RegisterView.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RegisterView.o src/gui/RegisterView.cpp

build/Cache.o: src/memory/Cache.cpp src/memory/Cache.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/memory/serialization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Cache.o src/memory/Cache.cpp

build/MainMemory.o: src/memory/MainMemory.cpp src/memory/MainMemory.h \
		src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/computer/Architecture.h \
		src/memory/serialization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainMemory.o src/memory/MainMemory.cpp

build/MemoryInterface.o: src/memory/MemoryInterface.cpp src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MemoryInterface.o src/memory/MemoryInterface.cpp

build/MemoryStructure.o: src/memory/MemoryStructure.cpp src/memory/MemoryStructure.h \
		src/memory/MemoryInterface.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MemoryStructure.o src/memory/MemoryStructure.cpp

build/QueryResult.o: src/memory/QueryResult.cpp src/memory/QueryResult.h \
		src/memory/Value.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QueryResult.o src/memory/QueryResult.cpp

build/Register.o: src/memory/Register.cpp src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/serialization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Register.o src/memory/Register.cpp

build/serialization.o: src/memory/serialization.cpp src/memory/serialization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/serialization.o src/memory/serialization.cpp

build/Baseline.o: src/pipeline/Baseline.cpp src/pipeline/Baseline.h \
		src/memory/Register.h \
		src/memory/QueryResult.h \
		src/memory/Value.h \
		src/memory/MemoryInterface.h \
		src/computer/Architecture.h \
		src/memory/MemoryStructure.h \
		src/memory/MainMemory.h \
		src/memory/Cache.h \
		src/computer/Status.h \
		src/pipeline/Banana.h \
		src/pipeline/spliceMachineCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Baseline.o src/pipeline/Baseline.cpp

build/spliceMachineCode.o: src/pipeline/spliceMachineCode.cpp src/pipeline/spliceMachineCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/spliceMachineCode.o src/pipeline/spliceMachineCode.cpp

build/StageData.o: src/pipeline/StageData.cpp src/pipeline/StageData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/StageData.o src/pipeline/StageData.cpp

build/qrc_pisa.o: build/qrc_pisa.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_pisa.o build/qrc_pisa.cpp

build/moc_TestAssembler.o: build/moc_TestAssembler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_TestAssembler.o build/moc_TestAssembler.cpp

build/moc_TestInstructionResolver.o: build/moc_TestInstructionResolver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_TestInstructionResolver.o build/moc_TestInstructionResolver.cpp

build/moc_Assembler.o: build/moc_Assembler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Assembler.o build/moc_Assembler.cpp

build/moc_CacheView.o: build/moc_CacheView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_CacheView.o build/moc_CacheView.cpp

build/moc_CodeEditor.o: build/moc_CodeEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_CodeEditor.o build/moc_CodeEditor.cpp

build/moc_EditorTab.o: build/moc_EditorTab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_EditorTab.o build/moc_EditorTab.cpp

build/moc_HighLighter.o: build/moc_HighLighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_HighLighter.o build/moc_HighLighter.cpp

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

build/moc_MemoryView.o: build/moc_MemoryView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MemoryView.o build/moc_MemoryView.cpp

build/moc_MiscDialog.o: build/moc_MiscDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MiscDialog.o build/moc_MiscDialog.cpp

build/moc_PreferenceDialog.o: build/moc_PreferenceDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_PreferenceDialog.o build/moc_PreferenceDialog.cpp

build/moc_RegisterView.o: build/moc_RegisterView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_RegisterView.o build/moc_RegisterView.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

