#!/usr/bin/env bash
make -s clean
qmake -project "DESTDIR = bin
OBJECTS_DIR = build
UI_DIR = src/gui
MOC_DIR = build
RCC_DIR = build

QT += widgets testlib
CONFIG += qt debug console c++11

copydata.commands = cp src/assembler/DefaultMacro src/assembler/DefaultAlias \$\$DESTDIR 
first.depends = \$(first) copydata
export(first.depends)
export(copydata.commands)
QMAKE_EXTRA_TARGETS += first copydata
" -after "
test{
    message(Configuring test build...)
    SOURCES -= src/main.cpp 

}
else{
    message(Normal build)
    SOURCES -= test/main.cpp \\
        src/pipeline/Pipeline.h \\
        src/pipeline/splicedMachineCode.h \\
        src/pipeline/StageData.h \\
        src/pipeline/PipelineGlobals.h \\
        src/pipeline/Pipeline.cpp 


}
SOURCES -= \$\$files(invisible/*)" 

