######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 20:58:19 2017
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .
QT += widgets

# Input
FORMS 	+= pisa.ui
HEADERS	+= MainWindow.h \
		ui_pisa.h
SOURCES += main.cpp \ 
		MainWindow.cpp
RESOURCES += rsc/pisa_resource.qrc
