//Size of each instruction
#define INSTRUCTION_SIZE 4

#define VECTOR_SIZE 64
#define NUMBER_OF_INTEGER_SCALAR_REGISTER 10
#define NUMBER_OF_FLOAT_SCALAR_REGISTER 10
#define NUMBER_OF_SYSTEM_REGISTER 4
#define NUMBER_OF_INTEGER_VECTOR 4
#define NUMBER_OF_FLOAT_VECTOR 4
#define TOTAL_NUMBER_OF_REGISTERS 32


